language: java
jdk: oraclejdk11
services:
  - postgresql
before_script:
      - psql -c 'create database webmonere_main;' -U postgres
before_install:
  - chmod +x mvnw
# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
install: true

script:   ./mvnw clean install
