spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/webmonere_main"
    username: ${DB_USER}
    password: ${DB_PASS}


    auth0:
      audience: https://localhost/
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: https://rajdeepdev.auth0.com/

